const std = @import("std");
var modules: struct {
    zon_tool: bool = false,
    sync: bool = false,
} = undefined;

pub fn getRegistry(allocator: std.mem.Allocator, files: []const []const u8) []const u8 {
    var w = std.Io.Writer.Allocating.init(allocator);
    var writer = &w.writer;
    _ = writer.write("//! autogenerated file.\n//! do not change.\n//! add to .gitignore if you want\n\n") catch unreachable;
    outer: for (0..files.len) |file| {
        for (0..file) |i| {
            if (std.mem.eql(u8, files[i], files[file])) {
                continue :outer;
            }
        }
        writer.print("pub const @\"{s}\" = @import(\"{s}\");\n", .{ files[file], files[file] }) catch unreachable;
    }
    return w.toOwnedSlice() catch unreachable;
}

pub const Scene = struct {
    entities: []const Entity = &[_]Entity{},
};

pub const Entity = struct {
    type: enum { single, group } = .single,
    scripts: []const Script = &[_]Script{},
};

pub const Script = union(enum) {
    script: struct {
        path: []const u8,
        data: []const u8, //ZON data
    },
};
pub fn getScript(path: []const u8, data: anytype, allocator: std.mem.Allocator) Script {
    var w = std.Io.Writer.Allocating.init(allocator);
    const writer = &w.writer;
    switch (@TypeOf(data)) {
        type => {
            std.zon.stringify.serialize(data{}, .{}, writer) catch unreachable;
        },
        else => {
            std.zon.stringify.serialize(data, .{}, writer) catch unreachable;
        },
    }
    return .{ .script = .{ .path = path, .data = w.toOwnedSlice() catch unreachable } };
}
pub fn makeScene(allocator: std.mem.Allocator, scene: Scene) []const u8 {
    const template = @embedFile("template.tp");
    return processTemplate(allocator, template, scene) catch unreachable;
}
pub fn addModule(b: *std.Build, scene: Scene, externalImports: []const std.Build.Module.Import, comptime name: []const u8, opts: anytype) Mod {
    for (externalImports) |i| {
        inline for (@typeInfo(@TypeOf(modules)).@"struct".fields) |f| {
            if (std.mem.eql(u8, i.name, f.name)) {
                @field(modules, f.name) = true;
            }
        }
    }
    var files = std.ArrayList([]const u8).empty;
    for (scene.entities) |entity| {
        for (entity.scripts) |script| {
            files.append(b.allocator, script.script.path) catch unreachable;
        }
    }
    var imports = std.ArrayList(std.Build.Module.Import).empty;
    imports.appendSlice(b.allocator, externalImports) catch unreachable;
    var registry = b.addWriteFile(b.pathFromRoot("registry.zig"), getRegistry(b.allocator, files.items));
    imports.append(b.allocator, .{
        .module = b.createModule(.{ .target = opts.target, .optimize = opts.optimize, .root_source_file = b.path("registry.zig"), .imports = imports.items }),
        .name = "registry",
    }) catch unreachable;
    const writeFiles = b.addWriteFiles();
    const sceneWriteFile = writeFiles.add(name ++ ".zig", makeScene(b.allocator, scene));
    for (0..scene.entities.len) |entity| {
        for (0..scene.entities[entity].scripts.len) |script| {
            var file = std.ArrayList(u8).empty;
            file.print(b.allocator, "entity{d}.script{d}.zon", .{ entity, script }) catch unreachable;
            _ = writeFiles.add(file.items, scene.entities[entity].scripts[script].script.data);
        }
    }
    const mod = b.createModule(.{ .root_source_file = sceneWriteFile, .imports = imports.items, .optimize = opts.optimize, .target = opts.target });
    writeFiles.step.dependOn(&registry.step);
    return .{ .module = mod, .step = &writeFiles.step };
}
const Mod = struct { module: *std.Build.Module, step: *std.Build.Step };

const Value = union(enum) {
    index: usize,
    string: []const u8,
};

const Scope = struct {
    vars: std.StringHashMap(Value),
    fn init(allocator: std.mem.Allocator) Scope {
        return .{ .vars = std.StringHashMap(Value).init(allocator) };
    }
    fn deinit(self: *Scope) void {
        self.vars.deinit();
    }
    fn get(self: *const Scope, name: []const u8) ?Value {
        return self.vars.get(name);
    }
    fn set(self: *Scope, name: []const u8, value: Value) !void {
        try self.vars.put(name, value);
    }
};

const PathResult = union(enum) {
    index: usize,
    string: []const u8,
    slice_len: usize,
};

fn evalPath(
    path: []const u8,
    scene: Scene,
    scope: *const Scope,
) PathResult {
    var it = std.mem.tokenizeAny(u8, path, ".[ ");
    const root = it.next() orelse @panic("empty path");

    if (std.mem.eql(u8, root, "modules")) {
        const field = it.next() orelse @panic("expected field after modules");
        const fname = std.mem.trim(u8, field, " .");
        const val =
            if (std.mem.eql(u8, fname, "zon_tool"))
                modules.zon_tool
            else if (std.mem.eql(u8, fname, "sync"))
                modules.sync
            else {
                std.log.err("fname: {s}", .{fname});
                unreachable;
            };
        return switch (@TypeOf(val)) {
            bool => .{ .index = @intFromBool(val) },
            else => @panic("unexpected modules field type"),
        };
    }

    if (!std.mem.eql(u8, root, "entities")) @panic("unknown path root");

    const idx_tok = it.next() orelse return .{ .slice_len = scene.entities.len };
    const idx_str = std.mem.trimEnd(u8, idx_tok, "]");
    const entity_idx = resolveIndex(idx_str, scope);

    const next = it.next() orelse return .{ .index = entity_idx };

    if (std.mem.eql(u8, next, "scripts")) {
        const sidx_tok = it.next() orelse return .{ .slice_len = scene.entities[entity_idx].scripts.len };
        const sidx_str = std.mem.trimEnd(u8, sidx_tok, "]");
        const script_idx = resolveIndex(sidx_str, scope);

        const leaf = it.next() orelse return .{ .index = script_idx };
        const lname = std.mem.trimEnd(u8, leaf, "]");
        if (script_idx == std.math.maxInt(usize)) return .{ .string = "" };

        if (std.mem.eql(u8, lname, "name")) {
            return .{ .string = scene.entities[entity_idx].scripts[script_idx].script.path };
        }

        @panic("unknown scripts leaf");
    }
    if (std.mem.eql(u8, next, "type")) {
        if (!std.mem.eql(u8, it.next() orelse @panic("expected comparison check after type"), "==")) @panic("expected single or group");
        const field = it.next() orelse @panic("expected single or group");
        if (std.mem.eql(u8, field, "single")) return .{ .index = @intFromBool(scene.entities[entity_idx].type == .single) };
        if (std.mem.eql(u8, field, "group")) return .{ .index = @intFromBool(scene.entities[entity_idx].type == .group) };
        @panic("expected single or group");
    }

    @panic("unknown entities field");
}

fn resolveIndex(tok: []const u8, scope: *const Scope) usize {
    if (tok[0] == '$') {
        const varname = tok[1..];
        const val = scope.get(varname) orelse {
            std.log.err("varname: {s}", .{varname});
            std.log.err("scope: {any}", .{scope.vars});
            @panic("undefined variable");
        };
        return switch (val) {
            .index => |i| i,
            .string => @panic("expected index variable, got string"),
        };
    }
    return std.fmt.parseInt(usize, tok, 10) catch @panic("bad index literal");
}

fn substituteVars(
    line: []const u8,
    scope: *const Scope,
    writer: *std.Io.Writer,
) !void {
    var i: usize = 0;
    while (i < line.len) {
        if (line[i] == '$') {
            var end = i + 1;
            while (end < line.len and (std.ascii.isAlphanumeric(line[end]) or line[end] == '_')) {
                end += 1;
            }
            const varname = line[i + 1 .. end];
            const val = scope.get(varname) orelse @panic("undefined variable in substitution");
            switch (val) {
                .index => |idx| try writer.print("{d}", .{idx}),
                .string => |s| try writer.writeAll(s),
            }
            i = end;
        } else {
            try writer.writeByte(line[i]);
            i += 1;
        }
    }
}

const DirectiveTag = enum { @"for", set, @"if", ifn, close };

const Directive = union(DirectiveTag) {
    @"for": struct { varname: []const u8, path: []const u8 },
    set: struct { varname: []const u8, path: []const u8 },
    @"if": struct { path: []const u8 },
    ifn: struct { path: []const u8 },
    close,
};

fn parseDirective(line: []const u8) ?Directive {
    const trimmed = std.mem.trim(u8, line, " \t");
    if (trimmed.len == 0 or trimmed[0] != '#') return null;

    const rest = std.mem.trim(u8, trimmed[1..], " \t");

    if (std.mem.eql(u8, rest, "}")) return .close;

    if (std.mem.startsWith(u8, rest, "for ")) {
        var it = std.mem.tokenizeScalar(u8, rest[4..], ' ');
        const varraw = it.next() orelse @panic("for: missing variable");
        if (varraw[0] != '$') @panic("for: variable must start with $");
        const varname = varraw[1..];
        const kw = it.next() orelse @panic("for: missing 'in'");
        if (!std.mem.eql(u8, kw, "in")) @panic("for: expected 'in'");
        const path = it.next() orelse @panic("for: missing path");
        return .{ .@"for" = .{ .varname = varname, .path = path } };
    }

    if (std.mem.startsWith(u8, rest, "set ")) {
        var it = std.mem.tokenizeScalar(u8, rest[4..], ' ');
        const varraw = it.next() orelse @panic("set: missing variable");
        if (varraw[0] != '$') @panic("set: variable must start with $");
        const varname = varraw[1..];
        const eq = it.next() orelse @panic("set: missing =");
        if (!std.mem.eql(u8, eq, "=")) @panic("set: expected =");
        const path_with_brace = it.next() orelse @panic("set: missing path");
        const path = std.mem.trimEnd(u8, path_with_brace, " {");
        return .{ .set = .{ .varname = varname, .path = path } };
    }

    if (std.mem.startsWith(u8, rest, "ifn ")) {
        const path = std.mem.trim(u8, rest[4..], " \t");
        return .{ .ifn = .{ .path = path } };
    }

    if (std.mem.startsWith(u8, rest, "if ")) {
        const path = std.mem.trim(u8, rest[3..], " \t");
        return .{ .@"if" = .{ .path = path } };
    }

    @panic("unknown directive");
}

const BlockKind = enum { @"for", set, @"if" };

const Block = struct {
    kind: BlockKind,
    emitting: bool,
};

pub fn processTemplate(
    allocator: std.mem.Allocator,
    template: []const u8,
    scene: Scene,
) ![]u8 {
    var allocating = std.Io.Writer.Allocating.init(allocator);
    var writer = &allocating.writer;

    var lines = std.ArrayList([]const u8).empty;
    defer lines.deinit(allocator);
    var lit = std.mem.splitScalar(u8, template, '\n');
    while (lit.next()) |l| try lines.append(allocator, l);

    var scope = Scope.init(allocator);
    defer scope.deinit();

    var pos: usize = 0;
    try processLines(lines.items, &pos, &scope, scene, writer, allocator, true);

    try writer.flush();
    return try allocating.toOwnedSlice();
}

fn processLines(
    lines: []const []const u8,
    pos: *usize,
    scope: *Scope,
    scene: Scene,
    writer: *std.Io.Writer,
    allocator: std.mem.Allocator,
    emitting: bool,
) !void {
    while (pos.* < lines.len) {
        const line = lines[pos.*];
        const dir = parseDirective(line);

        if (dir == null) {
            pos.* += 1;
            if (emitting) {
                try substituteVars(line, scope, writer);
                try writer.writeByte('\n');
            }
            continue;
        }

        switch (dir.?) {
            .close => {
                pos.* += 1;
                return;
            },

            .@"for" => |f| {
                pos.* += 1;
                const start = pos.*;
                const result = evalPath(f.path, scene, scope);
                const len = switch (result) {
                    .slice_len => |l| l,
                    else => @panic("for path must resolve to a slice"),
                };
                const old = scope.get(f.varname);
                var end_pos: usize = start;
                for (0..len) |idx| {
                    try scope.set(f.varname, .{ .index = idx });
                    end_pos = start;
                    try processLines(lines, &end_pos, scope, scene, writer, allocator, emitting);
                }
                if (len == 0) {
                    try scope.set(f.varname, .{ .index = std.math.maxInt(usize) });
                    end_pos = start;
                    try processLines(lines, &end_pos, scope, scene, writer, allocator, false);
                }
                pos.* = end_pos;
                if (old) |o| {
                    try scope.set(f.varname, o);
                } else {
                    _ = scope.vars.remove(f.varname);
                }
            },

            .set => |s| {
                pos.* += 1;
                const result = evalPath(s.path, scene, scope);
                const val: Value = switch (result) {
                    .string => |str| .{ .string = str },
                    .index => |i| .{ .index = i },
                    .slice_len => @panic("set path must resolve to a scalar"),
                };
                const old = scope.get(s.varname);
                try scope.set(s.varname, val);
                try processLines(lines, pos, scope, scene, writer, allocator, emitting);
                if (old) |o| {
                    try scope.set(s.varname, o);
                } else {
                    _ = scope.vars.remove(s.varname);
                }
            },

            .@"if" => |f| {
                pos.* += 1;
                const result = evalPath(f.path, scene, scope);
                const cond = switch (result) {
                    .index => |i| i != 0,
                    else => @panic("if path must resolve to a bool/index"),
                };
                try processLines(lines, pos, scope, scene, writer, allocator, emitting and cond);
            },

            .ifn => |f| {
                pos.* += 1;
                const result = evalPath(f.path, scene, scope);
                const cond = switch (result) {
                    .index => |i| i == 0,
                    else => @panic("ifn path must resolve to a bool/index"),
                };
                try processLines(lines, pos, scope, scene, writer, allocator, emitting and cond);
            },
        }
    }
}
