import itertools

def generfunc():
    script_type = 'registry.@"{0s}"'
    script_val = '(entity.*).script{2d}'
    script_ptr = '&' + script_val
    
    self_variants = [
        {"type": None, "val": None},                         # No self passed
        {"type": script_type, "val": script_val},            # Pass by value
        {"type": "*" + script_type, "val": script_ptr},      # Pass by pointer
        {"type": "*const " + script_type, "val": script_ptr} # Pass by const pointer
    ]

    extra_arg_map = {
        "f64": "time",
        "anytype": "entity",
        "std.mem.Allocator": "allocator.?",
        "std.Io": "io.?",
    }

    all_signatures = []
    
    extra_types = list(extra_arg_map.keys())
    
    for r in range(len(extra_types) + 1):
        for extra_combo in itertools.combinations(extra_types, r):
            for p in itertools.permutations(extra_combo):
                for self_var in self_variants:
                    types = []
                    vals = []
                    
                    # Self is always first
                    if self_var["type"]:
                        types.append(self_var["type"])
                        vals.append(self_var["val"])
                    
                    # Add the permuted extra args
                    for t in p:
                        types.append(t)
                        vals.append(extra_arg_map[t])
                    
                    sig_type = f"fn({', '.join(types)}) void"
                    sig_call = f"registry.@\"{{0s}}\".{{1s}}({', '.join(vals)})"
                    all_signatures.append((sig_type, sig_call))

    print('writer.print(')
    print('\\\\if(@hasDecl(registry.@"{0s}", "{1s}")){{')
    
    for sig_type, sig_call in all_signatures:
        # Avoid duplicate fn() void if generated by different loops
        if sig_type == "fn() void" and all_signatures.index((sig_type, sig_call)) != 0:
            continue
            
        print(f'\\\\if(@TypeOf(registry.@"{{0s}}".{{1s}}) == {sig_type}){sig_call};')
    
    print('\\\\}}', end="")
    print('\n, .{ s.path, func, script }) catch unreachable;')

if __name__ == "__main__":
    generfunc()
